---
spring:
  config:
    activate:
      on-profile: "default"
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/card_system_db
    username: alexei
    password: test
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      show-sql: false

  liquibase:
    enabled: true
    change-log: classpath:database/changelog/master.xml

app:
  jwt:
    secret: "VGhpc1lvdXJCYW5rQ2FyZFN5c3RlbVNlY3JldEtleUZvclNoYUFsZ29yaXRobXM="
    tokenExpiration: 5m
    refreshTokenExpiration: 25m
  scheduler:
    enabled: true
    expirationTokenDeleteInterval: PT30M
    expirationCardInterval: 4h
  card:
    expiration: 3d